### ISSUE TITLE
誤訳：シークレット回転という表現は利用しません

### ISSUE THREAD

**Issue by imurata** [Kong/docs.konghq.com-jp#40]
問題となるURL：
https://docs.jp.konghq.com/gateway/latest/kong-enterprise/secrets-management/secrets-rotation/

ドキュメントの左サイドバーに「シークレット回転」とありますが、こちらは「シークレットのローテーション」が適訳になると考えます。
![image](https://github.com/user-attachments/assets/98d8f2e6-0349-414a-b142-ec5bfbb3a444)

**Comment by shinichi-hashitani** [comment]
It is a translation issue.

For the time being, "シークレット回転" will be replaced with "ローテーション" because the suggested change "シークレットのローテーション" is too long in the contents navigation list. "ローテーション" only means "rotation," but it will make sense because the target is a sub-page of "シークレット管理 (Secret Management)".

**Comment by shinichi-hashitani** [comment]
There were several places using "回転" for "Rotation." All will be converted to "ローテーション."
